name: Deploy Production Server

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: sh deploy.sh

      - name: SCP Deploy
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: sftp://padopado.sakura.ne.jp:22/test
          ftp-username: padopado
          ftp-password: ${{ secrets.SFTP_PASSWORD }}
          known-hosts: padopado.sakura.ne.jp ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDEkboqp7Nrqclgk98qMOARevJEDKCzjFVb0s8uIQzMUelmo3S3+SeviBBCMeWS6HRS85F7IqXHWQTmytog+AlH8aVTP8KPqfQt61WZIx/n1fIWzuEr4VZKwxghGvjINbiW5XmDbunKEj0HbWqAzb9j1lPrr6TwMdLTfN4J6KUbeBEBPzxc8Ohg5P/SQiq+1+JGpD3GjeNaIDTDjWTbRROpVtoMJWzerCanDi8Kdwo+l020en23hjiQV4tLzA/atulL5FTSOeUqvyVJ3cj1HcLOdcIGh9wKj8xsHMmx1zwEIg6vTmSnbFF98Um68b1Ajt1uH+piRs736kMFU4eoxOkf
          local-dir: docs
          git-ftp-args: --insecure
